channels:
  - conda-forge
  - bioconda
  - ekirving
dependencies:
  - admixtools=6.0
  - biopython=1.78
  - graph-tool=2.35
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.3
  - pathos=0.2.6
  - pip=20.2.4
  - python-graphviz=0.14.2
  - python=3.8.6
  - r-admixturegraph=1.0.2
  - r-base=3.6.3
  - r-coda=0.19_4
  - r-data.table=1.13.2
  - r-fitr=0.1
  - r-ggplot2=3.3.2
  - r-gtools=3.8.2
  - r-neldermead=1.0_11
  - r-optimsimplex=1.0_7
  - r-raster=3.3_13
  - r-reshape2=1.4.4
  - r-rjson=0.2.20
  - r-scales=1.1.1
  - r-stringr=1.4.0
  - r-viridis=0.5.1
  - scipy=1.5.2
  - pip:
      - git+https://github.com/ekirving/qpbrute.git
